In [1]:
import tensorflow as tf
from tensorflow.keras.models import load_model
import pickle
import pandas as pd
import numpy as np


2025-06-25 14:34:41.420194: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [ ]:
###load the trained model pickle files all
rom tensorflow.keras.models import load_model
model = load_model('model.keras')

##load the encoder and scaler
with open('le.pkl','rb')as file:
    label_le=pickle.load(file)
with open('onehot_encoder_geo','rb')as file:
    label_encoder_geo=pickle.load(file)
with open('scaler','rb')as file:
    label_scaler=pickle.load(file)
    

In [7]:
#example input data
input_data = {
    'CreditScore': 600,
    'Geography': 'France',       # will be OneHotEncoded
    'Gender': 'Female',          # will be LabelEncoded
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000.00,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000.00
}



In [9]:
# One-hot encode the 'Geography' column using the fitted OneHotEncoder []==list of features
geo_encoded = label_encoder_geo.transform([[input_data['Geography']]]).toarray()

# Convert the one-hot encoded result into a DataFrame with proper column names
geo_encoded_df = pd.DataFrame(
    geo_encoded,
    columns=label_encoder_geo.get_feature_names_out(["Geography"])
)
geo_encoded_df

/opt/anaconda3/lib/python3.12/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [11]:
#convert the dict into dataframe
input_df=pd.DataFrame([input_data])
input_df


CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France  Female   40       3  60000.0              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1          50000.0

In [32]:
input_df['Gender'] = label_le.fit_transform(input_df['Gender'])  # Female = 0, Male = 1
input_df.head()

CreditScore Geography  Gender  Age  Tenure  Balance  NumOfProducts  \
0          600    France       0   40       3  60000.0              2   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1          50000.0

In [34]:
# Step 5: Concatenate with original data (drop 'Geography' column first) axis 1 to concaton colm ise
#and le for gender too
input_df = pd.concat([input_df.drop("Geography", axis=1), geo_encoded_df],axis=1)
input_df.head()

CreditScore  Gender  Age  Tenure  Balance  NumOfProducts  HasCrCard  \
0          600       0   40       3  60000.0              2          1   

   IsActiveMember  EstimatedSalary  Geography_France  Geography_Germany  \
0               1          50000.0               1.0                0.0   

   Geography_Spain  
0              0.0

In [36]:
input_scaled=label_scaler.transform(input_df)
input_scaled #all datas are i the form of arr nscaled acc to its mean

array([[-0.53598516, -1.09499335,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [38]:
#predict
prediction=model.predict(input_scaled)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 292ms/step


array([[0.04499928]], dtype=float32)

In [40]:
pred_prob=prediction[0][0]
prediction


array([[0.04499928]], dtype=float32)

In [42]:
if pred_prob >0.5:
    print("the customer is likely to churn")
else:
    print("the customer is not likely to churn")
    

the customer is not likely to churn


In [90]:
from tensorflow import keras

model = keras.models.load_model("model.keras", compile=False, safe_mode=False)


In [ ]:
##downloading package for streamlit for app.py run in terminal if u doinin vscode

In [94]:
!pip install streamlit --no-deps


In [96]:
!pip install blinker cachetools watchdog tzlocal numpy pandas toml


In [98]:
!streamlit --version


Streamlit, version 1.46.0


In [ ]:
!streamlit run app.py



  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://192.168.1.100:8501

2025-06-25 15:38:59.096638: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:380: InconsistentVersionWarning: Trying to unpickle estimator LabelEncoder from version 1.5.1 when using version 1.6.1. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/sklearn/base.py:380: InconsistentVersionWar